"""Pre-job checklist page — turns the relevant SOPs into a printable checklist."""

import re

import streamlit as st

from chat import get_llm, get_retriever
from rag.chain import LLMUnavailableError
from rag.checklist import checklist_pdf, generate_checklist


def render_checklist():
    st.title("✅ Pre-job safety checklist")
    st.caption(
        "Describe the job. DocuMind collects the permits, PPE, hazards and precautions from the "
        "relevant SOPs and turns them into a checklist you can tick off or print. Every line cites its SOP."
    )

    with st.form("checklist_form"):
        task = st.text_input("Job / task", placeholder="e.g. Entering the tuyere area during planned shutdown")
        area = st.text_input("Area / equipment", placeholder="e.g. Blast Furnace No. 2")
        submitted = st.form_submit_button("Generate checklist", type="primary")

    if submitted:
        if not task.strip():
            st.warning("Please describe the job first.")
        else:
            with st.spinner("Reading the relevant SOPs..."):
                try:
                    st.session_state.checklist = generate_checklist(
                        task.strip(), area.strip(), get_retriever(), get_llm(),
                        department=st.session_state.get("department"),
                    )
                except LLMUnavailableError as exc:
                    st.error(str(exc))
                except ValueError as exc:
                    st.error(f"The checklist could not be generated ({exc}). Please try again.")

    checklist = st.session_state.get("checklist")
    if not checklist:
        return
    if not checklist["sections"]:
        st.warning("The current SOPs don't cover this job. Please check with your Shift In-charge.", icon="📭")
        return

    st.subheader(checklist["title"])
    total = sum(len(s["items"]) for s in checklist["sections"])
    done = 0
    for s_idx, section in enumerate(checklist["sections"]):
        st.markdown(f"**{section['heading']}**")
        for i_idx, item in enumerate(section["items"]):
            if st.checkbox(item["text"], key=f"chk_{s_idx}_{i_idx}", help=f"Source: {item['citation']}"):
                done += 1
            st.caption(f"↳ {item['citation']}")
    st.progress(done / total if total else 0, text=f"{done} of {total} checks completed")

    if checklist.get("dropped"):
        st.info(f"{checklist['dropped']} suggested item(s) were removed because they did not point to an SOP excerpt.")

    slug = re.sub(r"[^a-z0-9]+", "_", checklist.get("task", "job").lower()).strip("_")[:40]
    st.download_button(
        "⬇ Download printable PDF",
        data=checklist_pdf(checklist),
        file_name=f"checklist_{slug}.pdf",
        mime="application/pdf",
    )
    st.caption(f"Generated by {checklist.get('model')} from {checklist.get('excerpts')} SOP excerpts.")
